### ISSUE TITLE
Couldn't download- Something went wrong

### ISSUE THREAD

**Issue by ufys1994** [czbiohub-sf/AIRRscape#3]
I tried to import the custom data, and after the upload was done, I clicked on the merge button; I clicked on steps 1 and step 2/3, and it doesn't allow me to download anything, the error mentioned in the title always pops up... I would like to know how I can analyze my data. I did not get enough information from the paper or the website.

Thanks,

**Comment by ewaltari** [comment]
Hi - I can confirm the custom upload currently isn't working on the web version of AIRRscape.
I will troubleshoot this issue, in the meantime you can still use the GitHub version locally. Thanks for the report!

**Comment by ewaltari** [comment]
Update - this is due to a 2023 update to dplr
https://github.com/tidyverse/dplyr/pull/6329

**Comment by ewaltari** [comment]
Added a fix for the above na_if bug, as well for an edge case (if users are importing datasets where clone_id column is numeric in one dataset but non-numeric in another)
-GitHub version is pushed
-online version will be redirected soon but also available now at 
https://czbiohub.shinyapps.io/airrscape34/
